version: '3'
services:
  zookeeper:
    image: 'zookeeper'
    ports:
      - "2181:2181"
    volumes:
      - data_zookeeper:/data
      - data_zookeeperlog:/datalog
  kafka:
    image: rwlv2-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094/tcp"
    volumes:
      - data_kafka:/var/kafka-logs
    environment:
      KAFKA_HOST: localhost
  keycloak:
    image: rwlv2-keycloak:latest
    ports:
      - "8580:8580"
  user:
    image: rwlv2-user:latest
    ports:
      - "8180:8180/tcp"
  article:
    image: rwlv2-article:latest
    ports:
      - "8280:8280/tcp"
  comments:
    image: rwlv2-comments:latest
    ports:
      - "8380:8380/tcp"

volumes:
  data_kafka:
  data_zookeeper:
  data_zookeeperlog:
